### PR TITLE
Added AXE Item to hotbar

### PR DESCRIPTION
**Pull request by dimaaac**
# ADDED AXE

I added the diamond_axe as it is one of the items that is not used. 
Replaced obsidian as diamond_axe.

### CODE REVIEW

**Comment by BlobTheKat** [comment]
What about obsidian

**Comment by prisect** [comment]
go to files changed

**Comment by BlobTheKat** [comment]
I mean you removed obsidian from the default inventory

**Comment by prisect** [comment]
can i add it to 10th

**Comment by BlobTheKat** [comment]
Sandstone is in 10 so put it in 11 please

**Comment by prisect** [comment]
ok, ill do a new one

**Pull request closed without merging**
